### ISSUE TITLE
Core dumped on an INI file

### ISSUE THREAD

**Issue by AloisMahdal** [Dieterbe/awmenu#1]
I use a minimalistic custom INI format for storing bookmarks.  When I feed one of my files to _awmenu_ it crashes as soon as I start typing.

**Comment by AloisMahdal** [comment]
The input file:

```
[www.bookmark]

    azw     = https://webmail.zxcvb.cz/
    mb      = https://online.mbank.cz/cs/Login
    fi      = https://www.fio.cz/scgi-bin/hermes/dz-internetbanking.cgi
    fm      = https://www.fastmail.fm/
    gm      = https://mail.google.com/
    mojeid  = https://alois-mahdal.mojeid.cz/
    oc      = https://oc.vornet.cz/
    va      = https://vm.axfone.eu/login.php
    sp      = http://www.starapekarna.cz
    pft     = https://pftadmin.profitux.cz/prihlasit
    totok   = http://totok.bplnet.home/
    _       = http://www.nic.cz/whois/?d=opravit.cz
    _       = http://www.nic.cz/whois/?d=fixnito.cz
    _       = http://www.forpsi.com
    _       = http://apps.evozi.com/apk-downloader/
    _       = http://www.colourlovers.com
    _       = https://books.google.cz/books?id=ndxudkqRhtIC
    _       = https://bugzilla.gnome.org/show_bug.cgi?id=587145
    _       = http://www.amazon.com/Didjeridu-Dharpa-Songs-Dreamtime-Seachnasigh/dp/B000007N9O/ref=ntt_mus_ep_dpi_2
    _       = http://dgshow.org/
    _       = https://securecoding.cert.org/confluence/display/seccode/CERT+C+Coding+Standard
    _       = http://www.ics.uci.edu/~fielding/pubs/dissertation/evaluation.htm#sec_6_2
    _       = http://mydevelopedworld.wordpress.com/2012/07/25/object-oriented-programming-inheritance-vs-composition/
    _sed    = http://www.grymoire.com/Unix/Sed.html#uh-0


# alkabot

    _abot   = http://caniuse.com/#search=resolution
    _abot   = http://www.htmlgoodies.com/beyond/css/article.php/3470341
    _abot   = http://edutechwiki.unige.ch/en/CSS_for_print_tutorial
    _abot   = https://github.com/h5bp/html5-boilerplate/issues/816#issuecomment-2512805
    _nginx  = http://www.root.cz/clanky/nginx-jako-reverzni-proxy-pro-apache/

    _ocbug  = https://github.com/owncloud/client/commit/38ef525d5ecde86c7899fbd6197ac95c3619b979

# imap2pop3

    _pop32imap = http://serverfault.com/search?q=imap+pop3+migration
    _pop32imap = http://serverfault.com/questions/497934/postfix-imap-pop3-migration-with-uidl-preservation/545150#545150
    _pop32imap = http://wiki2.dovecot.org/Migration/Dsync
```

The backtrace:

```
GNU gdb (GDB) Fedora 7.8.2-38.fc21
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./awmenu...(no debugging symbols found)...done.
(gdb) Starting program: /home/amahdal/vcs.upstream/awmenu/awmenu <maybe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGABRT, Aborted.
0x00007ffff531c8d7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55    return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) #0  0x00007ffff531c8d7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff531e53a in __GI_abort () at abort.c:89
#2  0x00007ffff535fda3 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff546f2f0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff536bbcd in __GI___libc_free (ptr=<optimized out>, str=0x7ffff546f318 "munmap_chunk(): invalid pointer", action=<optimized out>) at malloc.c:4974
#4  0x00007ffff536bbcd in __GI___libc_free (p=<optimized out>) at malloc.c:2821
#5  0x00007ffff536bbcd in __GI___libc_free (mem=<optimized out>) at malloc.c:2946
#6  0x00007ffff5df950f in g_free (mem=0x68d170) at gmem.c:190
#7  0x0000000000401da7 in midori_location_entry_render_text_cb ()
#8  0x00007ffff79b757a in IA__gtk_tree_view_column_cell_set_cell_data (tree_column=tree_column@entry=0x6e3840 [GtkTreeViewColumn], tree_model=0x68d170, iter=iter@entry=0x7fffffffc050, is_expander=0, is_expanded=0) at gtktreeviewcolumn.c:2593
#9  0x00007ffff799cc81 in validate_row (tree_view=tree_view@entry=0x6de310 [GtkTreeView], tree=tree@entry=0x73b1b0, node=node@entry=0x71a690, iter=iter@entry=0x7fffffffc050, path=path@entry=0x741a70)
    at gtktreeview.c:5781
#10 0x00007ffff799e4a2 in do_validate_rows (tree_view=0x6de310 [GtkTreeView], queue_resize=0)
    at gtktreeview.c:6341
#11 0x00007ffff799e876 in gtk_tree_view_size_request (widget=0x6de310 [GtkTreeView], requisition=0x6de348) at gtktreeview.c:2052
#12 0x00007ffff60f5c0e in g_cclosure_marshal_VOID__BOXEDv (closure=0x626c60, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x641180) at gmarshal.c:1160
#13 0x00007ffff60f2dd2 in _g_closure_invoke_va (closure=closure@entry=0x626c60, return_value=return_value@entry=0x0, instance=instance@entry=0x6de310, args=args@entry=0x7fffffffc3c8, n_params=1, param_types=0x641180) at gclosure.c:831
#14 0x00007ffff610cb00 in g_signal_emit_valist (instance=instance@entry=0x6de310, signal_id=signal_id@entry=18, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffc3c8) at gsignal.c:3218
#15 0x00007ffff610d89a in g_signal_emit_by_name (instance=instance@entry=0x6de310, detailed_signal=detailed_signal@entry=0x7ffff7adf8d9 "size-request") at gsignal.c:3405
#16 0x00007ffff790e934 in do_size_request (widget=widget@entry=0x6de310 [GtkTreeView])
    at gtksizegroup.c:628
#17 0x00007ffff790fb0a in _gtk_size_group_compute_requisition (widget=0x6de310 [GtkTreeView], requisition=requisition@entry=0x7fffffffc540) at gtksizegroup.c:828
#18 0x00007ffff79c5502 in IA__gtk_widget_size_request (widget=<optimized out>, requisition=requisition@entry=0x7fffffffc540) at gtkwidget.c:3939
#19 0x00007ffff79042be in gtk_scrolled_window_size_request (widget=0x687970 [GtkScrolledWindow], requisition=0x6879a8) at gtkscrolledwindow.c:1261
#20 0x00007ffff60f5c0e in g_cclosure_marshal_VOID__BOXEDv (closure=0x626c60, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x641180) at gmarshal.c:1160
#21 0x00007ffff60f2dd2 in _g_closure_invoke_va (closure=closure@entry=0x626c60, return_value=return_value@entry=0x0, instance=instance@entry=0x687970, args=args@entry=0x7fffffffc838, n_params=1, param_types=0x641180) at gclosure.c:831
#22 0x00007ffff610cb00 in g_signal_emit_valist (instance=instance@entry=0x687970, signal_id=signal_id@entry=18, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffc838) at gsignal.c:3218
#23 0x00007ffff610d89a in g_signal_emit_by_name (instance=instance@entry=0x687970, detailed_signal=detailed_signal@entry=0x7ffff7adf8d9 "size-request") at gsignal.c:3405
#24 0x00007ffff790e934 in do_size_request (widget=widget@entry=0x687970 [GtkScrolledWindow])
    at gtksizegroup.c:628
#25 0x00007ffff790fb0a in _gtk_size_group_compute_requisition (widget=0x687970 [GtkScrolledWindow], requisition=requisition@entry=0x7fffffffc9a0) at gtksizegroup.c:828
#26 0x00007ffff79c5502 in IA__gtk_widget_size_request (widget=<optimized out>, requisition=requisition@entry=0x7fffffffc9a0) at gtkwidget.c:3939
#27 0x00007ffff77d56bd in gtk_box_size_request (widget=<optimized out>, requisition=0x6ef2f8)
    at gtkbox.c:280
#28 0x00007ffff60f5c0e in g_cclosure_marshal_VOID__BOXEDv (closure=0x626c60, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x641180) at gmarshal.c:1160
#29 0x00007ffff60f2dd2 in _g_closure_invoke_va (closure=closure@entry=0x626c60, return_value=return_value@entry=0x0, instance=instance@entry=0x6ef2c0, args=args@entry=0x7fffffffcc98, n_params=1, param_types=0x641180) at gclosure.c:831
#30 0x00007ffff610cb00 in g_signal_emit_valist (instance=instance@entry=0x6ef2c0, signal_id=signal_id@entry=18, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffcc98) at gsignal.c:3218
#31 0x00007ffff610d89a in g_signal_emit_by_name (instance=instance@entry=0x6ef2c0, detailed_signal=detailed_signal@entry=0x7ffff7adf8d9 "size-request") at gsignal.c:3405
#32 0x00007ffff790e934 in do_size_request (widget=widget@entry=0x6ef2c0 [GtkVBox]) at gtksizegroup.c:628
#33 0x00007ffff790fb0a in _gtk_size_group_compute_requisition (widget=0x6ef2c0 [GtkVBox], requisition=requisition@entry=0x7fffffffcdf0) at gtksizegroup.c:828
#34 0x00007ffff79c5502 in IA__gtk_widget_size_request (widget=<optimized out>, requisition=requisition@entry=0x7fffffffcdf0) at gtkwidget.c:3939
#35 0x00007ffff7854b0d in gtk_frame_size_request (widget=0x687aa0 [GtkFrame], requisition=0x687ad8)
    at gtkframe.c:630
#36 0x00007ffff60f5c0e in g_cclosure_marshal_VOID__BOXEDv (closure=0x626c60, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x641180) at gmarshal.c:1160
#37 0x00007ffff60f2dd2 in _g_closure_invoke_va (closure=closure@entry=0x626c60, return_value=return_value@entry=0x0, instance=instance@entry=0x687aa0, args=args@entry=0x7fffffffd0d8, n_params=1, param_types=0x641180) at gclosure.c:831
#38 0x00007ffff610cb00 in g_signal_emit_valist (instance=instance@entry=0x687aa0, signal_id=signal_id@entry=18, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffd0d8) at gsignal.c:3218
#39 0x00007ffff610d89a in g_signal_emit_by_name (instance=instance@entry=0x687aa0, detailed_signal=detailed_signal@entry=0x7ffff7adf8d9 "size-request") at gsignal.c:3405
#40 0x00007ffff790e934 in do_size_request (widget=widget@entry=0x687aa0 [GtkFrame]) at gtksizegroup.c:628
#41 0x00007ffff790fb0a in _gtk_size_group_compute_requisition (widget=0x687aa0 [GtkFrame], requisition=requisition@entry=0x7fffffffd230) at gtksizegroup.c:828
#42 0x00007ffff79c5502 in IA__gtk_widget_size_request (widget=<optimized out>, requisition=requisition@entry=0x7fffffffd230) at gtkwidget.c:3939
#43 0x00007ffff79d87b5 in gtk_window_size_request (widget=<optimized out>, requisition=0x64e198)
    at gtkwindow.c:4968
#44 0x00007ffff60f5c0e in g_cclosure_marshal_VOID__BOXEDv (closure=0x626c60, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x641180) at gmarshal.c:1160
#45 0x00007ffff60f2e84 in _g_closure_invoke_va (closure=closure@entry=0x626c60, return_value=return_value@entry=0x0, instance=instance@entry=0x64e160, args=args@entry=0x7fffffffd518, n_params=<optimized out>, param_types=0x641180) at gclosure.c:831
#46 0x00007ffff610cb00 in g_signal_emit_valist (instance=instance@entry=0x64e160, signal_id=signal_id@entry=18, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffd518) at gsignal.c:3218
#47 0x00007ffff610d89a in g_signal_emit_by_name (instance=instance@entry=0x64e160, detailed_signal=detailed_signal@entry=0x7ffff7adf8d9 "size-request") at gsignal.c:3405
#48 0x00007ffff790e934 in do_size_request (widget=widget@entry=0x64e160 [GtkWindow])
    at gtksizegroup.c:628
#49 0x00007ffff790fb0a in _gtk_size_group_compute_requisition (widget=widget@entry=0x64e160 [GtkWindow], requisition=requisition@entry=0x7fffffffd670) at gtksizegroup.c:828
#50 0x00007ffff79c5502 in IA__gtk_widget_size_request (widget=widget@entry=0x64e160 [GtkWindow], requisition=requisition@entry=0x7fffffffd670) at gtkwidget.c:3939
#51 0x00007ffff79db40f in gtk_window_realize (widget=0x64e160 [GtkWindow]) at gtkwindow.c:4747
#52 0x00007ffff60f2e84 in _g_closure_invoke_va (closure=closure@entry=0x626b10, return_value=return_value@entry=0x0, instance=instance@entry=0x64e160, args=args@entry=0x7fffffffd900, n_params=<optimized out>, param_types=0x0) at gclosure.c:831
#53 0x00007ffff610cb00 in g_signal_emit_valist (instance=0x64e160, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd900) at gsignal.c:3218
#54 0x00007ffff610d34f in g_signal_emit (instance=instance@entry=0x64e160, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3365
#55 0x00007ffff79ce079 in IA__gtk_widget_realize (widget=0x64e160 [GtkWindow]) at gtkwidget.c:3561
#56 0x00007ffff79ce199 in IA__gtk_widget_realize (widget=0x687aa0 [GtkFrame]) at gtkwidget.c:3557
#57 0x00007ffff79ce199 in IA__gtk_widget_realize (widget=0x6ef2c0 [GtkVBox]) at gtkwidget.c:3557
#58 0x00007ffff79ce199 in IA__gtk_widget_realize (widget=0x687970 [GtkScrolledWindow])
    at gtkwidget.c:3557
#59 0x00007ffff79ce199 in IA__gtk_widget_realize (widget=0x6de310 [GtkTreeView]) at gtkwidget.c:3557
#60 0x00007ffff7825a49 in _gtk_entry_completion_resize_popup (completion=completion@entry=0x63d5b0 [GtkEntryCompletion]) at gtkentrycompletion.c:1407
#61 0x00007ffff7825ece in _gtk_entry_completion_popup (completion=0x63d5b0 [GtkEntryCompletion])
    at gtkentrycompletion.c:1506
#62 0x00007ffff781df85 in gtk_entry_completion_timeout (data=<optimized out>) at gtkentry.c:9305
#63 0x00007ffff74acae7 in gdk_threads_dispatch (data=0x6fc680, 
    data@entry=<error reading variable: value has been optimized out>) at gdk.c:534
#64 0x00007ffff5df4263 in g_timeout_dispatch (source=0x70d560, callback=<optimized out>, user_data=<optimized out>) at gmain.c:4520
#65 0x00007ffff5df37fb in g_main_context_dispatch (context=0x63c110) at gmain.c:3111
#66 0x00007ffff5df37fb in g_main_context_dispatch (context=context@entry=0x63c110) at gmain.c:3710
#67 0x00007ffff5df3b98 in g_main_context_iterate (context=0x63c110, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3781
#68 0x00007ffff5df3ec2 in g_main_loop_run (loop=0x6f4db0) at gmain.c:3975
#69 0x00007ffff7894ec7 in IA__gtk_main () at gtkmain.c:1268
#70 0x0000000000402165 in main ()
(gdb) quit
A debugging session is active.

    Inferior 1 [process 18585] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```
